---
- name: Retrieve temporary root password (RedHat)
  shell: "cat /var/log/mysqld.log \
    | grep 'A temporary password is generated for root@localhost:' \
    | sed 's/.*root@localhost: //'"
  become: true
  register: temp_root_password

- debug:
    var: temp_root_password

- name: Set temporary password policy level (RedHat)
  shell: "mysql -u root -p'{{ temp_root_password.stdout }}' \
    --connect-expired-password -e 'SET GLOBAL {{ item }};'"
  loop:
    "{{ mysql_password_policy_settings[mysql_version_parts['major']|string]|flatten(levels=1) }}"
  when: |-
    mysql_password_policy_settings is defined and
    mysql_allow_simple_passwords

- name: DEBUG (vv) - MySQL temp password (RedHat)
  debug:
    msg: "MySQL temp password: {{ temp_root_password.stdout }}"
    verbosity: 2

- name: Set MySQL root user password to mysql_root_password (RedHat)
  shell: "mysql -u root -p'{{ temp_root_password.stdout }}' \
    --connect-expired-password -e 'alter user root@localhost identified \
    by \"{{ mysql_root_password }}\";'"
