---
# # - name: Install dotnet4.5.2
# #   win_chocolatey:
# #     name: dotnet4.5.2
# #     state: present
# #     # when: mysql_version_parts['major'] | int < 8

# # Source: https://github.com/ansible/ansible/issues/27155

# - name: check if Windows8.1-KB2999226-x64.msu hotfix has been applied
#   win_shell: Get-Hotfix -Id KB2999226
#   register: hotfix_status
#   ignore_errors: true

# - name: show hotfix status
#   debug:
#     var: hotfix_status

# # Unfortunately you can't use wusa directly to install windows updates.
# # see https://support.microsoft.com/en-us/kb/2773898 for details
# # you have to unpack the update file and then use dism.exe to install the cab

# - name: unpack the hotfix if needed
#   win_shell: 'wusa C:\deployment\current\Windows8.1-KB2999226-x64.msu /extract:C:\deployment\archive'
#   when: hotfix_status.rc == 1

# - name: use dism to install the cab containing the hotfix
#   win_shell: 'dism.exe /online /add-package /PackagePath:C:\deployment\archive\Windows8.1-KB2999226-x64.cab'
#   when: hotfix_status.rc == 1

# - name: ensure Microsoft Visual C++ 2015 x64 Additional Runtime is present
#   win_package:
#     name: Microsoft Visual C++ 2015 x64 Additional Runtime
#     path: 'C:/Program Files/FireDaemon Session 0 Viewer/vc_redist.x64.exe'
#     state: present
#     product_id: '{BC958BD2-5DAC-3862-BB1A-C1BE0790438D}'
#     arguments: "/install /passive /norestart /quiet"

# #  Info on the hotfix that needs to be applied first
# # see http://stackoverflow.com/questions/33265663/api-ms-win-crt-runtime-l1-1-0-dll-is-missing-when-open-office-file
# # the hotfix is KB2999226

# - name: Install vcredist2013
#   win_chocolatey:
#     name: vcredist2013
#     state: present
#   when: mysql_version_parts['major'] | int < 8

# - name: Install vcredist2015
#   become: true
#   win_chocolatey:
#     name: vcredist2015
#     state: present
#   ignore_errors: true
#   when: mysql_version_parts['major'] | int >= 8
