---
- name: Ensure MySQL service is stopped
  service:
    name: '{{ mysql_service_name }}'
    state: stopped
  become: true

- name: Ensure MySQL service is started
  service:
    name: '{{ mysql_service_name }}'
    state: started
    enabled: true
  become: true
