---
- name: Retrieve temporary root password
  shell: "cat /var/log/mysqld.log \
    | grep 'A temporary password is generated for root@localhost:' \
    | sed 's/.*root@localhost: //'"
  register: temp_root_password

- name: Set password policy to allow simple passwords
  shell: "mysql -u root -p'{{ temp_root_password.stdout }}' \
    --connect-expired-password -e '{{ item }}'"
  with_items:
    "{{ mysql_password_policy_settings[mysql_version_parts['major']|string] }}"
  when: mysql_allow_simple_passwords

- name: Set MySQL root user password using temp password
  shell: "mysql -u root -p'{{ temp_root_password.stdout }}' \
    --connect-expired-password -e 'alter user root@localhost identified \
    by \"{{ mysql_root_password }}\";'"
