---
- name: Retrieve temporary root password
  shell: "cat /var/log/mysqld.log \
    | grep 'A temporary password is generated for root@localhost:' \
    | sed 's/.*root@localhost: //'"
  register: temp_root_password

- name: Set password policy level (temporary)
  shell: "mysql -u root -p'{{ temp_root_password.stdout }}' \
    --connect-expired-password -e 'SET GLOBAL {{ item }};'"
  with_items:
    "{{ mysql_password_policy_settings[mysql_version_parts['major']|string] }}"
  when: |-
    mysql_password_policy_settings is defined and
    mysql_allow_simple_passwords

- name: DEBUG - MySQL temp password
  debug:
    msg: "MySQL temp password: {{ temp_root_password.stdout }}"

- name: Set MySQL root user password to mysql_root_password
  shell: "mysql -u root -p'{{ temp_root_password.stdout }}' \
    --connect-expired-password -e 'alter user root@localhost identified \
    by \"{{ mysql_root_password }}\";'"
