---
- name: Retrieve temporary root password
  shell: "cat /var/log/mysqld.log | grep 'A temporary password is generated for root@localhost:' | sed 's/.*root@localhost: //'"
  register: temp_root_password

- name: DEBUG - temporary password
  debug:
    msg: '{{ temp_root_password.stdout }}'

- name: Set password policy to allow simple passwords
  shell: "mysql -u root -p'{{ temp_root_password.stdout }}' --connect-expired-password -e '{{ item }}'"
  with_items:
    - SET GLOBAL validate_password.check_user_name = OFF;
    - SET GLOBAL validate_password.mixed_case_count = 0;
    - SET GLOBAL validate_password.special_char_count = 0;
    - SET GLOBAL validate_password.number_count = 0;
    - SET GLOBAL validate_password.length = 0;
  when: mysql_allow_simple_passwords

- name: Set MySQL root user password using temp password
  shell: "mysql -u root -p'{{ temp_root_password.stdout }}' --connect-expired-password -e 'alter user root@localhost identified by \"{{ mysql_root_password }}\";'"
