---
- name: Create MySQL users (Windows)
  win_command: "\"{{ mysql_executable_path }}\\mysql.exe\" -u root \
    -p{{ mysql_root_password }} -e \
    \"CREATE USER IF NOT EXISTS '{{ item.name }}'@'{{ item.host }}';\""
  loop: "{{ mysql_users }}"

- name: Assign password to MySQL users (Windows)
  win_command: "\"{{ mysql_executable_path }}\\mysql.exe\" -u root \
    -p{{ mysql_root_password }} -e \
    \"SET PASSWORD FOR '{{ item.name }}'@'{{ item.host }}' = '{{ item.password }}';\""
  loop: "{{ mysql_users }}"
