---
- name: Create MySQL databases (Unix)
  shell: "{{ mysql_executable_path }}/mysql \
    -u root -p'{{ mysql_root_password }}' \
    -e 'CREATE DATABASE {{ item }};'"
  loop: '{{ mysql_databases }}'
