---
- name: Set temporary password policy level (Unix)
  shell: "mysql -u root -p'{{ mysql_root_password }}' -e 'SET GLOBAL {{ item }};'"
  with_items:
    "{{ mysql_password_policy_settings[mysql_version_parts['major']|string] }}"
  when: |-
    mysql_password_policy_settings is defined and
    mysql_allow_simple_passwords

- name: Create users (Unix)
  shell: "{{ mysql_executable_path }}/mysql \
    -u root -p'{{ mysql_root_password }}' \
    -e \"CREATE USER IF NOT EXISTS '{{ item.name }}'@'{{ item.host }}';\""
  loop: '{{ mysql_users }}'
  changed_when: false

- name: Assign password to MySQL users (Unix)
  shell: "{{ mysql_executable_path }}/mysql \
    -u root -p'{{ mysql_root_password }}' \
    -e \"SET PASSWORD FOR '{{ item.name }}'@'{{ item.host }}' = '{{ item.password }}';\""
  loop: '{{ mysql_users }}'
  changed_when: false
