---
- name: Create users
  shell: "{{ mysql_executable_path }}/mysql \
    -u root -p'{{ mysql_root_password }}' \
    -e 'CREATE USER {{ item.name }}@{{ item.host }} \
    IDENTIFIED BY \"{{ item.password }}\";'"
  loop: '{{ mysql_users }}'
