---
- name: Define regex pattern for installer filename (Darwin)
  set_fact:
    regex_string: "^{{ mysql_installer_name_prefix }}\
    -{{ mysql_version_regex }}\
    -{{ mysql_installer_name_insert }}10\\.\\d+\
    -{{ mysql_installer_name_suffix }}\
    \\.dmg"

- name: DEBUG - regex pattern for installer filename (Darwin)
  debug:
    msg: '{{ regex_string }}'
    verbosity: 2

- name: Find possible installer filenames (Darwin)
  find:
    paths: '{{ mysql_installers_path_on_controller }}'
    recurse: false
    patterns: '{{ regex_string }}'
    use_regex: true
  register: found_files
  failed_when: found_files.files | length == 0
  delegate_to: 127.0.0.1

- name: Set mysql_installer_filename (Darwin)
  set_fact:
    mysql_installer_filename: '{{ (found_files.files | last).path | basename }}'

- name: Check for installer on target (Darwin)
  stat:
    path: "{{ mysql_installers_path_on_target }}/{{ mysql_installer_filename }}"
  register: installer

- block:

    - name: Copy installer to target (Darwin)
      copy:
        src: "{{ mysql_installers_path_on_controller }}/{{ mysql_installer_filename }}"
        dest: "{{ mysql_installers_path_on_target }}"

    - name: Check for installer on target (Darwin)
      stat:
        path: "{{ mysql_installers_path_on_target }}/{{ mysql_installer_filename }}"
      register: installer
      failed_when: installer.stat.exists != true

  when: installer.stat.exists != true
