---
- name: Stop MySQL service
  shell: 'launchctl unload -F /Library/LaunchDaemons/com.oracle.oss.mysql.mysqld.plist'
  become: true

- name: Create temporary init script to reset root password for 5.7.6+
  shell: "echo \"ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';\" > /tmp/mysql-init.txt"

- name: Start MySQL with init-file
  shell: "launchctl load -F /Library/LaunchDaemons/com.oracle.oss.mysql.mysqld.plist --init-file=/tmp/mysql-init.txt"
  become: true

- name: Stop MySQL service
  shell: 'launchctl unload -F /Library/LaunchDaemons/com.oracle.oss.mysql.mysqld.plist'
  become: true

- name: Stop MySQL service
  shell: 'launchctl load -F /Library/LaunchDaemons/com.oracle.oss.mysql.mysqld.plist'
  become: true
