---
- name: Stop MySQL service
  shell: 'launchctl unload -F {{ mysql_darwin_launchdaemon_filepath }}'
  become: true

- name: Create temporary init script to reset root password for 5.7.6+
  shell: "echo \"ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';\" > /tmp/mysql-init.txt"

- name: Start MySQL with init-file
  shell: "launchctl load -F {{ mysql_darwin_launchdaemon_filepath }} --init-file=/tmp/mysql-init.txt"
  become: true

- name: Stop MySQL service
  shell: 'launchctl unload -F {{ mysql_darwin_launchdaemon_filepath }}'
  become: true

- name: Start MySQL service
  shell: 'launchctl load -F {{ mysql_darwin_launchdaemon_filepath }}'
  become: true
