---
- name: Add MySQL Repo
  yum:
    name: '{{ mysql_installers_path_on_target }}/{{ mysql_installer_filename }}'
    state: present
  become: true

- name: Install yum-config-manager
  yum:
    name: yum-utils
    state: installed
  become: true

- name: Disable default subrepository
  shell: 'yum-config-manager --disable mysql80-community'
  become: true

- name: Enable version-specific subrepository
  shell: "yum-config-manager --enable \
    mysql{{ mysql_version_parts['major']|string }}\
    {{ mysql_version_parts['minor']|string }}-community"
  become: true

- name: Install MySQL
  yum:
    name: mysql-community-server
    state: installed
  become: true
  register: mysql_install

- name: Install MySQL-python library
  yum:
    name: MySQL-python
    state: installed
  become: true
