---
- name: Get Installed MySQL Version (Unix)
  command: mysql --version
  register: mysql_version_result
  changed_when: false

- name: MySQL Version
  vars:
    msg: |
      {{ mysql_version_result.stdout | trim }}
  debug:
    msg: "{{ msg.split('\n')[:-1] }}"
  changed_when: false
