---
- name: Set MySQL authentication plugin string
  set_fact:
    mysql_authentication_config_string: |-
      {% if mysql_authentication_plugin == 'mysql_native_password' -%}
      Use Legacy Authentication Method (Retain MySQL 5.x Compatibility)
      {%- else -%}
      Use Strong Password Encryption (RECOMMENDED)
      {%- endif %}
