---
- name: Create MySQL databases (Windows)
  win_shell: |
    $mySql = "{{ mysql_executable_path }}\mysql.exe"
    $mySqlParams = '-u', 'root', '-p', '{{ mysql_root_password }}'
    $mySqlCommand = "CREATE DATABASE {{ item }};"
    Start-Process -FilePath $mySql -ArgumentList "$mySqlParams", '-e', "$mySqlCommand" -Wait -NoNewWindow
  loop: '{{ mysql_databases }}'
