---
- block:

  - name: Stop MySQL service
    shell: 'launchctl unload -F {{ mysql_darwin_launchdaemon_filepath }}'
    become: true

  - name: Create temporary init script to reset root password for 5.7.6+
    shell: "echo \"ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';\" > /tmp/mysql-init.txt"

  - name: Start MySQL with init-file
    shell: "launchctl load -F {{ mysql_darwin_launchdaemon_filepath }} --init-file=/tmp/mysql-init.txt"
    become: true

  - name: Stop MySQL service
    shell: 'launchctl unload -F {{ mysql_darwin_launchdaemon_filepath }}'
    become: true

  when: |-
    mysql_version_parts['minor'] | int == 7 and
    mysql_version_parts['patch'] | int >= 6

- name: Start MySQL service
  shell: 'launchctl load -F {{ mysql_darwin_launchdaemon_filepath }}'
  become: true

- name: Reset root user password for 5.7.5 and earlier
  shell: "{{ mysql_mac_destination_path }}/mysqladmin -u root password '{{ mysql_root_password }}'"
  when: |-
    mysql_version_parts['minor'] | int == 7 and
    mysql_version_parts['patch'] | int < 6
