---
- name: Mount disk image containing installer (Darwin)
  shell: "hdiutil attach -noautoopen -noverify
    '{{ mysql_installers_path_on_target }}/{{ mysql_installer_filename }}'
    | grep /Volumes | cut -f 3"
  register: mount_dmg_results

- name: Set mysql_mounted_volume_path
  set_fact:
    mysql_mounted_volume_path: '{{ mount_dmg_results.stdout }}'

- name: Find possible package names in mysql_mounted_volume_path
  find:
    paths: '{{ mysql_mounted_volume_path }}'
    recurse: false
  register: found_pkgs

- name: Set mysql_installer_package_path
  set_fact:
    mysql_installer_package_path: '{{ (found_pkgs.files | last).path }}'

- name: Install MySQL
  become: true
  command: "installer -pkg \"{{ mysql_installer_package_path }}\" -target /"
  register: mysql_install

- name: Unmount disk image
  command: "hdiutil detach \"{{ mysql_mounted_volume_path }}\""

- name: Add mysql to /etc/paths
  become: true
  command: "sh -c \"echo '{{ mysql_darwin_executable_path }}' >> /etc/paths\""
